import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "swiper/swiper-bundle.css";
import { Bricolage_Grotesque } from "next/font/google";
import { register } from "swiper/element/bundle";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
const secondaryFont = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-grotesque",
  display: "swap",
  adjustFontFallback: false,
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const sfProdisplay = localFont({
  src: "./fonts/SfProDisplay.otf",
  variable: "--font-sfPro",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Techwave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  register();
  return (
    <html lang="en" className="overflow-x-hidden">
      {/* <head>
        <link rel="icon" href="/favicon.png" type="image/png" /> 
      </head> */}
      <body
        className={`${secondaryFont.variable} ${geistSans.variable} ${geistMono.variable} ${sfProdisplay.variable}  min-h-screen font flex flex-col`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
